In [2]:
import os
import numpy as np
import librosa.display

In [3]:
# n_row = 20
# n_col = 431
# features = np.zeros([1, n_row*n_col])
# features.shape

(1, 8620)

In [4]:
# for file in os.listdir('.'):
#     if file.endswith(".wav"):
#         y, sr = librosa.load(file)
#         mfccs = librosa.feature.mfcc(y, sr=sr, n_mfcc = n_row)
#         print("---------------- Filename and its feature size:", file, mfccs.shape)
        
#         if len(mfccs[0])>n_col:
#             mfccs = mfccs[:, 0:n_col]
#             print("Shorten feature size to:", mfccs.shape)
            
#         if len(mfccs[0])<n_col:
#             t=np.zeros([n_row, n_col-len(mfccs[0])])
#             mfccs = np.hstack((mfccs, t))
#             print("Lengthen feature size to:", mfccs.shape)
            
#         features = np.vstack((features, mfccs.reshape(1,-1)))

---------------- Filename and its feature size: c001.wav (20, 431)
---------------- Filename and its feature size: c002.wav (20, 431)
---------------- Filename and its feature size: c003.wav (20, 432)
Shorten feature size to: (20, 431)
---------------- Filename and its feature size: c004.wav (20, 431)
---------------- Filename and its feature size: c005.wav (20, 431)
---------------- Filename and its feature size: c006.wav (20, 433)
Shorten feature size to: (20, 431)
---------------- Filename and its feature size: c007.wav (20, 431)
---------------- Filename and its feature size: c008.wav (20, 431)
---------------- Filename and its feature size: c009.wav (20, 431)
---------------- Filename and its feature size: c010.wav (20, 431)
---------------- Filename and its feature size: c011.wav (20, 431)
---------------- Filename and its feature size: c012.wav (20, 432)
Shorten feature size to: (20, 431)
---------------- Filename and its feature size: c013.wav (20, 431)
---------------- Filenam

---------------- Filename and its feature size: v011.wav (20, 431)
---------------- Filename and its feature size: v012.wav (20, 431)
---------------- Filename and its feature size: v013.wav (20, 431)
---------------- Filename and its feature size: v014.wav (20, 431)
---------------- Filename and its feature size: v015.wav (20, 431)
---------------- Filename and its feature size: v016.wav (20, 430)
Lengthen feature size to: (20, 431)
---------------- Filename and its feature size: v017.wav (20, 431)
---------------- Filename and its feature size: v018.wav (20, 434)
Shorten feature size to: (20, 431)
---------------- Filename and its feature size: v019.wav (20, 432)
Shorten feature size to: (20, 431)
---------------- Filename and its feature size: v020.wav (20, 431)
---------------- Filename and its feature size: v021.wav (20, 432)
Shorten feature size to: (20, 431)
---------------- Filename and its feature size: v022.wav (20, 431)
---------------- Filename and its feature size: v023.wa

In [5]:
# #Remove the first line
# features = features[1:, :]
# #Save the feature set to a file
# np.save("20features.npy", features)

In [5]:
features=np.load("20features.npy")
features.shape

(200, 17240)

In [6]:
labels=np.hstack((np.zeros((100,),dtype=int),np.ones((100,),dtype=int)))

In [7]:
print('Class labels:', np.unique(labels))

Class labels: [0 1]


In [76]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn import metrics
for i in range(1, 16):
    X_train, X_test, y_train, y_test = train_test_split(features, labels , test_size=.2, random_state=i)
    #Create the SVM model
    clf = SVC(C=100, kernel = 'rbf')

    #Fit the model for the data
    clf.fit(X_train, y_train)

    #Make the prediction
    y_pred = clf.predict(X_test)
    
    print ('--- Case', i, '---')
#     # Model Accuracy: 
#     print("Accuracy: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
#     # Model Precision: 
#     print("Precision: {:.2f}".format(metrics.precision_score(y_test, y_pred)))
#     # Model Recall: 
#     print("Sensitivity (Recall): {:.2f}".format(metrics.recall_score(y_test, y_pred)))
    
#     # Confusion matrix
#     print(metrics.confusion_matrix(y_test,y_pred))
#     print(metrics.classification_report(y_test,y_pred))
    
    # Cross-validation
    accuracies = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 5)
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies.mean()))

--- Case 1 ---
5 fold cross-validation -> Accuracy: 0.74
--- Case 2 ---
5 fold cross-validation -> Accuracy: 0.66
--- Case 3 ---
5 fold cross-validation -> Accuracy: 0.71
--- Case 4 ---
5 fold cross-validation -> Accuracy: 0.59
--- Case 5 ---
5 fold cross-validation -> Accuracy: 0.73
--- Case 6 ---
5 fold cross-validation -> Accuracy: 0.69
--- Case 7 ---
5 fold cross-validation -> Accuracy: 0.72
--- Case 8 ---
5 fold cross-validation -> Accuracy: 0.69
--- Case 9 ---
5 fold cross-validation -> Accuracy: 0.74
--- Case 10 ---
5 fold cross-validation -> Accuracy: 0.72
--- Case 11 ---
5 fold cross-validation -> Accuracy: 0.66
--- Case 12 ---
5 fold cross-validation -> Accuracy: 0.68
--- Case 13 ---
5 fold cross-validation -> Accuracy: 0.74
--- Case 14 ---
5 fold cross-validation -> Accuracy: 0.71
--- Case 15 ---
5 fold cross-validation -> Accuracy: 0.73


In [75]:
for i in range(1, 16):
    X_train, X_test, y_train, y_test = train_test_split(features, labels , test_size=.2, random_state=i)
    #Create the SVM model
    clf = SVC(C=100, kernel = 'rbf', random_state = 1)

    #Fit the model for the data
    clf.fit(X_train, y_train)

    #Make the prediction
    y_pred = clf.predict(X_test)
    
    print ('--- Case', i, '---')
    # Model Accuracy: 
    print("Accuracy: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    # Model Precision: 
    print("Precision: {:.2f}".format(metrics.precision_score(y_test, y_pred)))
    # Model Recall: 
    print("Sensitivity (Recall): {:.2f}".format(metrics.recall_score(y_test, y_pred)))
    
    # Confusion matrix
    print(metrics.confusion_matrix(y_test,y_pred))
    print(metrics.classification_report(y_test,y_pred))

--- Case 1 ---
Accuracy: 0.57
Precision: 0.50
Sensitivity (Recall): 0.82
[[ 9 14]
 [ 3 14]]
              precision    recall  f1-score   support

           0       0.75      0.39      0.51        23
           1       0.50      0.82      0.62        17

    accuracy                           0.57        40
   macro avg       0.62      0.61      0.57        40
weighted avg       0.64      0.57      0.56        40

--- Case 2 ---
Accuracy: 0.88
Precision: 0.82
Sensitivity (Recall): 0.88
[[21  3]
 [ 2 14]]
              precision    recall  f1-score   support

           0       0.91      0.88      0.89        24
           1       0.82      0.88      0.85        16

    accuracy                           0.88        40
   macro avg       0.87      0.88      0.87        40
weighted avg       0.88      0.88      0.88        40

--- Case 3 ---
Accuracy: 0.62
Precision: 0.58
Sensitivity (Recall): 0.61
[[14  8]
 [ 7 11]]
              precision    recall  f1-score   support

           0   

In [79]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn import metrics
for i in range(1, 16):
    X_train, X_test, y_train, y_test = train_test_split(features, labels , test_size=.2, random_state=i)
    #Create the SVM model
    clf = SVC(C=100, kernel = 'linear')

    #Fit the model for the data
    clf.fit(X_train, y_train)

    #Make the prediction
    y_pred = clf.predict(X_test)
    
    print ('--- Case', i, '---')
#     # Model Accuracy: 
#     print("Accuracy: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
#     # Model Precision: 
#     print("Precision: {:.2f}".format(metrics.precision_score(y_test, y_pred)))
#     # Model Recall: 
#     print("Sensitivity (Recall): {:.2f}".format(metrics.recall_score(y_test, y_pred)))
    
#     # Confusion matrix
#     print(metrics.confusion_matrix(y_test,y_pred))
#     print(metrics.classification_report(y_test,y_pred))
    
    # Cross-validation
    accuracies = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 5)
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies.mean()))


--- Case 1 ---
5 fold cross-validation -> Accuracy: 0.66
--- Case 2 ---
5 fold cross-validation -> Accuracy: 0.57
--- Case 3 ---
5 fold cross-validation -> Accuracy: 0.55
--- Case 4 ---
5 fold cross-validation -> Accuracy: 0.54
--- Case 5 ---
5 fold cross-validation -> Accuracy: 0.67
--- Case 6 ---
5 fold cross-validation -> Accuracy: 0.62
--- Case 7 ---
5 fold cross-validation -> Accuracy: 0.66
--- Case 8 ---
5 fold cross-validation -> Accuracy: 0.60
--- Case 9 ---
5 fold cross-validation -> Accuracy: 0.67
--- Case 10 ---
5 fold cross-validation -> Accuracy: 0.61
--- Case 11 ---
5 fold cross-validation -> Accuracy: 0.59
--- Case 12 ---
5 fold cross-validation -> Accuracy: 0.62
--- Case 13 ---
5 fold cross-validation -> Accuracy: 0.68
--- Case 14 ---
5 fold cross-validation -> Accuracy: 0.65
--- Case 15 ---
5 fold cross-validation -> Accuracy: 0.61


In [80]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

plt.figure(figsize=(10,5))
X_pca = PCA().fit_transform(X)
plt.title('PCA - Iris dataset')
plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
plt.scatter(X_pca[:,0],X_pca[:,1],c=data.target)
_ = plot_pca_correlation_graph(X,data.feature_names)

ModuleNotFoundError: No module named 'mlxtend'