In [1]:
import numpy as np
features=np.load("20features.npy")

In [2]:
labels=np.hstack((np.zeros((100,),dtype=int),np.ones((100,),dtype=int)))

In [3]:
from sklearn.model_selection import cross_val_score, StratifiedShuffleSplit
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [4]:
# Logistic Regression classifier
clf=LogisticRegression(max_iter = 300)
# Decision Tree classifier
clf_tree = DecisionTreeClassifier()
# Random Forest classifier
clf_forest = RandomForestClassifier(n_estimators=100)
# Support Vector Machine classifier, linear kernel
svm_l = SVC(C=100, kernel = 'linear')
# Support Vector Machine classifier, polynomial kernel
svm_p = SVC(C=100, kernel = 'poly')
# Support Vector Machine classifier, rbf kernel
svm_r = SVC(C=100, kernel = 'rbf')
# Gaussian Naive Bayes classifier
clf_nb=GaussianNB()

In [5]:
np.random.seed(1)
# number of test case
tc = 5
sss = StratifiedShuffleSplit(n_splits=tc, test_size=.3, random_state=1)
sss.get_n_splits(features, labels)
for train_index, test_index in sss.split(features, labels):
    print ('!--------------------!--------------------!--------------------!--------------------!--------------------!')
    print("Test using:", test_index)
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    # Decision Tree
    print ("-------------------- Decision Tree classifier: --------------------")
    clf_tree.fit(X_train, y_train)
    y_pred = clf_tree.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
#     # Cross-validation 5 folds
#     accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
#     print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
#     # Random Forest
#     print ("-------------------- Random Forest classifier: --------------------")
#     clf_forest.fit(X_train, y_train)
#     y_pred = clf_forest.predict(X_test)
    
#     print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
#     print(metrics.confusion_matrix(y_test,y_pred))
#     # Cross-validation 10 folds
#     accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
#     print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
#     # Cross-validation 10 folds
#     accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
#     print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
#     # SVM Linear
#     print ("-------------------- SVM classifier, linear kernel: --------------------")
#     svm_l.fit(X_train, y_train)
#     y_pred = svm_l.predict(X_test)
    
#     print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
#     print(metrics.confusion_matrix(y_test,y_pred))
#     # Cross-validation 10 folds
#     accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
#     print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
#     # Cross-validation 10 folds
#     accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
#     print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
#     # SVM Poly
#     print ("-------------------- SVM classifier, polynomial kernel: --------------------")
#     svm_p.fit(X_train, y_train)
#     y_pred = svm_p.predict(X_test)
    
#     print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
#     print(metrics.confusion_matrix(y_test,y_pred))
#     # Cross-validation 10 folds
#     accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
#     print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
#     # Cross-validation 10 folds
#     accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
#     print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
#     # SVM RBF
#     print ("-------------------- SVM classifier, RBF function kernel: --------------------")
#     svm_r.fit(X_train, y_train)
#     y_pred = svm_r.predict(X_test)
    
#     print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
#     print(metrics.confusion_matrix(y_test,y_pred))
#     # Cross-validation 10 folds
#     accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
#     print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
#     # Cross-validation 10 folds
#     accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
#     print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))


!--------------------!--------------------!--------------------!--------------------!--------------------!
Test using: [ 50 185  96  68 184 106 145 177  22 190 123 143 130 113   9 120  72 175
  85 124  20 194   7  16 136   6 170 102  75   1  29 107 112  25  28  71
 191  37   5  14 132  12  61 152  79 110  18 176 172 193  76 157 168  11
  13  63 121 181  64  57]
-------------------- Decision Tree classifier: --------------------
Accuracy and confusion matrix: 0.62
[[19 11]
 [12 18]]
10 fold cross-validation -> Accuracy: 0.58
!--------------------!--------------------!--------------------!--------------------!--------------------!
Test using: [ 58 186 137  75 127  26  11 194 143 177 121 105 134  16 162  42  70 178
   6 119  63   2 138  52 133  98  49 107 104 140 190  37  78  35  21  95
 139 108  86 167 130 169  18   0 151  28 182 181 179  36 142 148  14  27
 146  22  50  94  32  97]
-------------------- Decision Tree classifier: --------------------
Accuracy and confusion matrix: 0.53
[[

In [34]:
np.random.seed(1)
# number of test case
tc = 5
sss = StratifiedShuffleSplit(n_splits=tc, test_size=.25, random_state=1)
sss.get_n_splits(features, labels)
for train_index, test_index in sss.split(features, labels):
    print ('!--------------------!--------------------!--------------------!--------------------!--------------------!')
    print("Test using:", test_index)
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    # Decision Tree
    print ("-------------------- Decision Tree classifier: --------------------")
    clf_tree.fit(X_train, y_train)
    y_pred = clf_tree.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # Random Forest
    print ("-------------------- Random Forest classifier: --------------------")
    clf_forest.fit(X_train, y_train)
    y_pred = clf_forest.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # SVM Linear
    print ("-------------------- SVM classifier, linear kernel: --------------------")
    svm_l.fit(X_train, y_train)
    y_pred = svm_l.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # SVM Poly
    print ("-------------------- SVM classifier, polynomial kernel: --------------------")
    svm_p.fit(X_train, y_train)
    y_pred = svm_p.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # SVM RBF
    print ("-------------------- SVM classifier, RBF function kernel: --------------------")
    svm_r.fit(X_train, y_train)
    y_pred = svm_r.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))


!--------------------!--------------------!--------------------!--------------------!--------------------!
Test using: [123  50 172   1 106 110 193 120 152  29  96  11 130 136 185  28  13 107
   5 102 176 113  85 191  18 143  76  71  14 177   9 170  64  75 145  16
  25  79   6 168  37 175  20 190 121 157  68  72  12 194]
-------------------- Decision Tree classifier: --------------------
Accuracy and confusion matrix: 0.58
[[14 11]
 [10 15]]
5 fold cross-validation -> Accuracy: 0.61
10 fold cross-validation -> Accuracy: 0.72
-------------------- Random Forest classifier: --------------------
Accuracy and confusion matrix: 0.84
[[20  5]
 [ 3 22]]
5 fold cross-validation -> Accuracy: 0.61
10 fold cross-validation -> Accuracy: 0.79
-------------------- SVM classifier, linear kernel: --------------------
Accuracy and confusion matrix: 0.70
[[19  6]
 [ 9 16]]
5 fold cross-validation -> Accuracy: 0.60
10 fold cross-validation -> Accuracy: 0.83
-------------------- SVM classifier, polynomial 

In [32]:
np.random.seed(1)
# number of test case
tc = 5
sss = StratifiedShuffleSplit(n_splits=tc, test_size=.2, random_state=1)
sss.get_n_splits(features, labels)
for train_index, test_index in sss.split(features, labels):
    print ('!--------------------!--------------------!--------------------!--------------------!--------------------!')
    print("Test using:", test_index)
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    
    # Decision Tree
    print ("-------------------- Decision Tree classifier: --------------------")
    clf_tree.fit(X_train, y_train)
    y_pred = clf_tree.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # Random Forest
    print ("-------------------- Random Forest classifier: --------------------")
    clf_forest.fit(X_train, y_train)
    y_pred = clf_forest.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # SVM Linear
    print ("-------------------- SVM classifier, linear kernel: --------------------")
    svm_l.fit(X_train, y_train)
    y_pred = svm_l.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # SVM Poly
    print ("-------------------- SVM classifier, polynomial kernel: --------------------")
    svm_p.fit(X_train, y_train)
    y_pred = svm_p.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))
    
    # SVM RBF
    print ("-------------------- SVM classifier, RBF function kernel: --------------------")
    svm_r.fit(X_train, y_train)
    y_pred = svm_r.predict(X_test)
    
    print("Accuracy and confusion matrix: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
    print(metrics.confusion_matrix(y_test,y_pred))
    # Cross-validation 10 folds
    accuracies5 = cross_val_score(estimator = clf_tree, X = X_train, y = y_train, cv = 5)   
    print("5 fold cross-validation -> Accuracy: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))



!--------------------!--------------------!--------------------!--------------------!--------------------!
Test using: [143   1 106  75 185 194 152 176 130  50  29   6 191 121 136  25  28 120
  37 172  76 193  18 175  71 102   5  79  20 177 190  11  72 145 107   9
 170  16  12  64]
-------------------- Decision Tree classifier: --------------------
Accuracy and confusion matrix: 0.55
[[10 10]
 [ 8 12]]
5 fold cross-validation -> Accuracy: 0.62
10 fold cross-validation -> Accuracy: 0.81
-------------------- Random Forest classifier: --------------------
Accuracy and confusion matrix: 0.80
[[17  3]
 [ 5 15]]
5 fold cross-validation -> Accuracy: 0.59
10 fold cross-validation -> Accuracy: 0.73
-------------------- SVM classifier, linear kernel: --------------------
Accuracy and confusion matrix: 0.65
[[14  6]
 [ 8 12]]
5 fold cross-validation -> Accuracy: 0.62
10 fold cross-validation -> Accuracy: 0.76
-------------------- SVM classifier, polynomial kernel: --------------------
Accuracy an

In [49]:
np.random.seed(1)
# number of test case
tc = 5
sss = StratifiedShuffleSplit(n_splits=tc, test_size=.25, random_state=1)
sss.get_n_splits(features, labels)
for train_index, test_index in sss.split(features, labels):
    print ('!--------------------!--------------------!--------------------!--------------------!--------------------!')
    print("Test using:", test_index)
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

    #Fit the model for the data
#     clf.fit(X_train, y_train)
    clf_nb.fit(X_train, y_train)

    #Make the prediction
    y_pred = clf_nb.predict(X_test)
    
    print ('--- --- --- --- --- --- ---')
    # Model Accuracy: 
    print("Accuracy: {:.2f}".format(metrics.accuracy_score(y_test, y_pred)))
        
    # Confusion matrix
    print(metrics.confusion_matrix(y_test,y_pred))
        
    # Cross-validation 5 folds        
    accuracies = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 5)
    print("5 fold cross-validation: {:.2f}".format(accuracies5.mean()))
    # Cross-validation 10 folds
    accuracies10 = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10, scoring='accuracy')    
    print("10 fold cross-validation -> Accuracy: {:.2f}".format(accuracies10.mean()))

!--------------------!--------------------!--------------------!--------------------!--------------------!
Test using: [123  50 172   1 106 110 193 120 152  29  96  11 130 136 185  28  13 107
   5 102 176 113  85 191  18 143  76  71  14 177   9 170  64  75 145  16
  25  79   6 168  37 175  20 190 121 157  68  72  12 194]
--- --- --- --- --- --- ---
Accuracy: 0.84
[[21  4]
 [ 4 21]]
5 fold cross-validation: 0.57
10 fold cross-validation -> Accuracy: 0.61
!--------------------!--------------------!--------------------!--------------------!--------------------!
Test using: [ 37 133 182 108  11 130  87   6  52 199  36 195  46 127 188  32 109 140
  50  21  58   0 138 148 105  22 146  16 178 103  63 107  92  35 181 137
  70 169 177  27  93 151 167  49  18 191  75  28 143  14]
--- --- --- --- --- --- ---
Accuracy: 0.72
[[19  6]
 [ 8 17]]
5 fold cross-validation: 0.57
10 fold cross-validation -> Accuracy: 0.61
!--------------------!--------------------!--------------------!--------------------